[0m00:27:32.646378 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f327e0bc8e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f327d25ea40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f327d25e9e0>]}


============================== 00:27:32.652116 | 07f69e9e-2b55-445b-8f70-5440af41a31f ==============================
[0m00:27:32.652116 [info ] [MainThread]: Running with dbt=1.9.3
[0m00:27:32.652859 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/elhassan/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:27:32.653620 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/elhassan/airflow/scripts/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:27:32.657379 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.08886138, "process_in_blocks": "48832", "process_kernel_time": 0.14674, "process_mem_max_rss": "90196", "process_out_blocks": "8", "process_user_time": 1.535886}
[0m00:27:32.658205 [debug] [MainThread]: Command `dbt run` failed at 00:27:32.658071 after 0.09 seconds
[0m00:27:32.658677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f327e0bc8e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f327d25ebc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f327d25ea40>]}
[0m00:27:32.659151 [debug] [MainThread]: Flushing usage events
[0m00:27:33.318239 [debug] [MainThread]: An error was encountered while trying to flush usage events
